api/urls.py
from django.urls import path, include, re_path

from .views import TaskListView, SubTaskListView
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi

schema_view = get_schema_view(
    openapi.Info(
        title="TO DO LIST API",
        default_version="v0"
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)

app_name = 'api'

urlpatterns = [
    re_path(r'^swagger(?P<format>\.json|\.yaml)$', schema_view.without_ui(cache_timeout=0), name='schema-json'),
    re_path(r'^swagger/$', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    re_path(r'^redoc/$', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
    path('tasks/', TaskListView.as_view()),
    path('subtasks/<int:pk>/', SubTaskListView.as_view())
]

to_do/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('to_do_list.urls')),
    path('api-auth/', include('rest_framework.urls')),
    path('api/v0/', include('api.urls'))
]

to_do_list/urls.py
from django.urls import path, include

from .views import index, TaskEditView, TaskDeleteView, TaskCreateView, SubTaskEditView

app_name = 'to_do_list'

urlpatterns = [
    path('', index, name='index'),
    path('update_task/<int:pk>/', TaskEditView.as_view(), name='update_task'),
    path('update_subtask/<int:pk>', SubTaskEditView.as_view(), name='update_subtask'),
    path('delete/<int:pk>/', TaskDeleteView.as_view(), name='delete'),
    path('add', TaskCreateView.as_view(), name='add'),
]

api/models.py
from django.db import models

# Create your models here.

to_do_list/models.py
from django.db import models


class Tasks(models.Model):
    title = models.CharField(max_length=120, blank=False, verbose_name='Цель')
    is_active = models.BooleanField(default=True, blank=False)
    published = models.DateField(auto_now_add=True, db_index=True)

    def __str__(self):
        return f"{self.title}"

    class Meta:
        verbose_name_plural = 'Цели'
        verbose_name = 'Цель'
        ordering = ['-published']


class Subtasks(models.Model):
    goals = models.ForeignKey(Tasks, on_delete=models.CASCADE, related_name='subtasks', verbose_name='Цель')
    description = models.CharField(max_length=255, blank=True, verbose_name='Описание')
    name = models.CharField(max_length=120, db_index=True, verbose_name='Задача')
    complete = models.BooleanField(default=False, verbose_name='Выполнено')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = 'Задачи'
        verbose_name = 'Задача'
        ordering = ['pk']

to_do_list/forms.py
from django.forms import ModelForm, CharField, Textarea
from .models import Tasks, Subtasks


class TaskForm(ModelForm):
    class Meta:
        model = Tasks
        fields = ('title',)
        labels = {'title': 'Цель'}


class SubtaskForm(ModelForm):
    description = CharField(required=False, widget=Textarea(attrs={'rows': 4, 'cols': 40}), label='Описание')

    class Meta:
        model = Subtasks
        fields = ('name', 'description', 'goals', 'complete')

api/views.py
from rest_framework.response import Response
from rest_framework.views import APIView
from .serializer import TaskListSerializer, Tasks, SubtaskListSerializer, Subtasks


class TaskListView(APIView):
    def get(self, request):
        tasks = Tasks.objects.all()
        serializer = TaskListSerializer(tasks, many=True)
        return Response(serializer.data)


class SubTaskListView(APIView):
    def get(self, request, pk):
        subtask = Subtasks.objects.filter(goals__id=pk)
        serializer = SubtaskListSerializer(subtask, many=True)
        return Response(serializer.data)

to_do_list/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic import DeleteView, UpdateView, CreateView
from .forms import TaskForm, SubtaskForm

from .models import Tasks, Subtasks



class TaskCreateView(CreateView):
    template_name = 'to_do_list/create.html'
    form_class = TaskForm
    success_url = reverse_lazy('to_do_list:index')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context


class TaskDeleteView(DeleteView):
    model = Tasks
    success_url = '/'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context


class TaskEditView(UpdateView):
    template_name = 'to_do_list/task_form.html'
    model = Tasks
    form_class = TaskForm
    success_url = '/'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['subtasks'] = Subtasks.objects.all()
        return context


class SubTaskEditView(UpdateView):
    template_name = 'to_do_list/subtask_form.html'
    model = Subtasks
    form_class = SubtaskForm
    success_url = '/'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context


def index(request):
    tasks = Tasks.objects.all()

    form = SubtaskForm()

    if request.method == 'POST' and not request.is_ajax():
        form = SubtaskForm(request.POST)
        if form.is_valid():
            form.save()
        return redirect('/')

    if request.method == 'POST' and request.is_ajax():
        sub_id = request.POST.get('getdata', None)
        subtask = Subtasks.objects.get(id=sub_id)
        subtask.delete()

    context = {
        'tasks': tasks,
        'form': form,
    }
    return render(request, 'to_do_list/index.html', context=context)

to_do_list/templates/layout/basic.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css"
          rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x"
          crossorigin="anonymous">
    <meta charset="UTF-8">
    <title>{% block title %} Главная {% endblock %}</title>
</head>
<body>
<section>
    {% block content %}
    {% endblock %}
</section>
</body>
</html>

to_do_list/templates/to_do_list/create.html
{% extends 'layout/basic.html' %}
{% block title %}Добавить цель{% endblock %}
{% block content %}
<h2>Добавить цель</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Добавить">
</form>
{% endblock %}

to_do_list/templates/to_do_list/index.html
{% extends 'layout/basic.html' %}
{% block content %}

<h1 align="center"><a href="{% url 'to_do_list:add' %}">&#43;</a></h1>
{% for task in tasks %}
<p>
    <div class="container overflow-hidden">
        <button class="btn btn-primary" type="button"
                data-bs-toggle="collapse"
                data-bs-target="#multiCollapseExample{{ forloop.counter }}"
                aria-expanded="false"
                aria-controls="multiCollapseExample{{ forloop.counter }}">{{task.title}}
        </button>
            {{ task.published }}
        <div class="row">
            <div class="col">
<p>
    <div class="collapse multi-collapse" id="multiCollapseExample{{ forloop.counter }}">
        <div class="card card-body">

            {% for subtask in task.subtasks.all %}
            <div class="card card-body">
            {% if subtask.complete %}
<p><i><s><a href="{% url 'to_do_list:update_subtask' pk=subtask.pk %}">{{subtask.name }}</a></s></i></p>
{% else %}
<p><a href="{% url 'to_do_list:update_subtask' pk=subtask.pk %}">{{subtask.name}}</a></p>
{% if subtask.description %}
<div align="center"><i><b>{{subtask.description}}</b></i></div>
{% endif %}
{% endif %}

<div>

    <p>
        <button id="delete-subtask" class="delete-button btn btn-danger" task_id="{{ subtask.id }}">
            &#215;
        </button>
    </p>
</div>
</div>
{% endfor %}

<form method="POST" action="/">
    {% csrf_token %}
    <div class="mb-3">
        <input type="text" name="name" class="form-control">
        <input type="hidden" name="goals" value="{{task.id}}">
    </div>
    <p>
        <button class="btn btn-primary" type="submit" name="add_subtask">Добавить задачу</button>
    </p>

</form>
</div>
</div></p>
</div>

</div>
<p>
    <a href="{% url 'to_do_list:update_task' pk=task.pk %}" class="btn btn-warning" type="button">&#9999;</a>
    <a href="{% url 'to_do_list:delete' pk=task.pk %}" class="btn btn-danger" type="button">&#215;</a>
</p>
</div>
</p>
{% endfor %}


<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"
        integrity="sha512-894YE6QWD5I59HgZOGReFYm4dnWc1Qt5NtvYSaNcOP+u1T9qYdvdihz0PPSiiqn/+/3e7Jo4EaG7TubfWGUrMQ=="
        crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<script>

    const deleteButtons = document.querySelectorAll('.delete-button');

    for (i = 0; i < deleteButtons.length; i++) {
      deleteButtons[i].addEventListener("click", function() {
        var delId = this.getAttribute('task_id');
        $.ajax({
          data: {'getdata': delId},
          method: 'POST',
          beforeSend: function (jqXHR) {
                  jqXHR.setRequestHeader("X-CSRFToken", document.querySelector('[name=csrfmiddlewaretoken]').value);
          },
          success: function (res) {
              console.log(res.data)
          },
          error: function (err) {
              console.error(err)
          },
          complete: function () {
                window.location = '{% url 'to_do_list:index' %}'
            },
        })
      });
    }





</script>
{% endblock content %}

to_do_list/templates/to_do_list/subtask_form.html
{% extends 'layout/basic.html' %}
{% block title %}Исправление{% endblock %}
{% block content %}
<a href="{% url 'to_do_list:index' %}">&#8592; Назад</a>
<h2>Исправление задачи</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Сохранить">
</form>
{% endblock %}

to_do_list/templates/to_do_list/task_form.html
{% extends 'layout/basic.html' %}
{% block title %}Исправление{% endblock %}
{% block content %}
<h2>Исправление</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Исправить">
</form>
{% endblock %}

to_do_list/templates/to_do_list/tasks_confirm_delete.html
{% extends "layout/basic.html" %}

{% block title %}Удаление{% endblock %}
{% block content %}
<h2>Удаление</h2>
<p>Цель: {{ tasks.title }}</p>
<form method="post">
    {% csrf_token %}
    <input type="submit" value="Удалить">
</form>
{% endblock %}